apiVersion: apps/v1
kind: Deployment
metadata:
  name: necro-automobilia-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: necro-automobilia-client
  template:
    metadata:
      labels:
        app: necro-automobilia-client
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: necro-automobilia-client
        image: linkedmink/necro-automobilia-client
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        env:
        - name: USER_SERVICE_URL
          value: "https://[Your Host]"
        - name: NECRO_AUTOMOBILIA_URL
          value: "https://[Your Host]"
        - name: JWT_PUBLIC_KEY
          value: "[Base64(PEM) If empty, the JWT token will be decoded without verification]"
        - name: GOOGLE_MAPS_API_KEY
          value: "[See https://developers.google.com/maps/gmp-get-started]"
---
apiVersion: v1
kind: Service
metadata:
  name: necro-automobilia-client
spec:
  ports:
  - port: 80
  selector:
    app: necro-automobilia-client
