export const stateMap = new Map();

stateMap.set("Alabama","AL");
stateMap.set("Alaska","AK");
stateMap.set("Alberta","AB");
stateMap.set("American Samoa","AS");
stateMap.set("Arizona","AZ");
stateMap.set("Arkansas","AR");
stateMap.set("Armed Forces (AE)","AE");
stateMap.set("Armed Forces Americas","AA");
stateMap.set("Armed Forces Pacific","AP");
stateMap.set("British Columbia","BC");
stateMap.set("California","CA");
stateMap.set("Colorado","CO");
stateMap.set("Connecticut","CT");
stateMap.set("Delaware","DE");
stateMap.set("District Of Columbia","DC");
stateMap.set("Florida","FL");
stateMap.set("Georgia","GA");
stateMap.set("Guam","GU");
stateMap.set("Hawaii","HI");
stateMap.set("Idaho","ID");
stateMap.set("Illinois","IL");
stateMap.set("Indiana","IN");
stateMap.set("Iowa","IA");
stateMap.set("Kansas","KS");
stateMap.set("Kentucky","KY");
stateMap.set("Louisiana","LA");
stateMap.set("Maine","ME");
stateMap.set("Manitoba","MB");
stateMap.set("Maryland","MD");
stateMap.set("Massachusetts","MA");
stateMap.set("Michigan","MI");
stateMap.set("Minnesota","MN");
stateMap.set("Mississippi","MS");
stateMap.set("Missouri","MO");
stateMap.set("Montana","MT");
stateMap.set("Nebraska","NE");
stateMap.set("Nevada","NV");
stateMap.set("New Brunswick","NB");
stateMap.set("New Hampshire","NH");
stateMap.set("New Jersey","NJ");
stateMap.set("New Mexico","NM");
stateMap.set("New York","NY");
stateMap.set("Newfoundland","NF");
stateMap.set("North Carolina","NC");
stateMap.set("North Dakota","ND");
stateMap.set("Northwest Territories","NT");
stateMap.set("Nova Scotia","NS");
stateMap.set("Nunavut","NU");
stateMap.set("Ohio","OH");
stateMap.set("Oklahoma","OK");
stateMap.set("Ontario","ON");
stateMap.set("Oregon","OR");
stateMap.set("Pennsylvania","PA");
stateMap.set("Prince Edward Island","PE");
stateMap.set("Puerto Rico","PR");
stateMap.set("Quebec","QC");
stateMap.set("Rhode Island","RI");
stateMap.set("Saskatchewan","SK");
stateMap.set("South Carolina","SC");
stateMap.set("South Dakota","SD");
stateMap.set("Tennessee","TN");
stateMap.set("Texas","TX");
stateMap.set("Utah","UT");
stateMap.set("Vermont","VT");
stateMap.set("Virgin Islands","VI");
stateMap.set("Virginia","VA");
stateMap.set("Washington","WA");
stateMap.set("West Virginia","WV");
stateMap.set("Wisconsin","WI");
stateMap.set("Wyoming","WY");
